 #
 # $Id: Makefile,v 1.3 1998/11/04 07:13:47 alc Exp $
 #
ARCH	= rs6k_mpl3

CC	= mpcc
CFLAGS	= -g -O

FC	= mpxlf
FFLAGS	= -g -O -qextname

MACHDEP_OBJS= common_symbol.o
MACHDEP_LIBS=

all: Jacobi.mpl

include ../.common

common_symbol.o: $(TmkLIB)/support/common_symbol
	cp $(TmkLIB)/support/common_symbol $@
