 #
 # $Id: Makefile,v 1.1 1997/12/23 22:03:38 alc Exp $
 #
ARCH	= alpha_linux2

CC	= gcc
CFLAGS	= -g -O2

MACHDEP_OBJS= getopt.o
MACHDEP_LIBS= -lm

all: water.udp

include ../.common

getopt.o: $(TmkLIB)/support/getopt.c
	$(CC) $(CFLAGS) -c $(TmkLIB)/support/getopt.c
