 #
 # $Id: Makefile,v 1.1 1998/08/21 06:27:47 alc Exp $
 #
ARCH	= sparc_sunos5

CC	= cc
CFLAGS	= -g -O

MACHDEP_OBJS=
MACHDEP_LIBS= -lsocket -lnsl

all: barrier.udp diff.udp lock.udp page.udp

include ../.common
