 #
 # $Id: Makefile,v 1.1 1997/12/08 03:25:40 alc Exp $
 #
ARCH	= rs6k_aix4

CC	= cc
CFLAGS	= -g -O

MACHDEP_OBJS=
MACHDEP_LIBS= -lm

LL	= /usr/lpp/LoadL/nfs

all:
	@if [ -f $(TmkLIB)/libTmk_udp.a    ]; then $(MAKE) raytrace.udp    ; fi
	@if [ -f $(TmkLIB)/libTmk_udp_ll.a ]; then $(MAKE) raytrace.udp_ll ; fi

include ../.common
