 #
 # $Id: Makefile,v 1.1 1997/12/08 07:44:59 alc Exp $
 #
ARCH	= i386_bsdi3

CC	= cc
CFLAGS	= -O2

FC	= f77
FFLAGS  = -O3

MACHDEP_OBJS= common_symbol.o
MACHDEP_LIBS= -lcompat

all: Jacobi.udp

include ../.common

common_symbol.o: $(TmkLIB)/support/common_symbol.s
	$(AS) -o $@ $(TmkLIB)/support/common_symbol.s
