 #
 # $Id: Makefile,v 1.2 1997/12/23 08:39:06 alc Exp $
 #
ARCH	= alpha_osf4

CC	= cc
CFLAGS	= -migrate -g3 -O

MACHDEP_OBJS=
MACHDEP_LIBS=

all: barrier.udp cond.udp diff.udp lock.udp page.udp

include ../.common
