/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "estructura.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

InfoAuto *
solicitarviaje_1(PosicionPasajero arg1,  CLIENT *clnt)
{
	static InfoAuto clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, solicitarViaje,
		(xdrproc_t) xdr_PosicionPasajero, (caddr_t) &arg1,
		(xdrproc_t) xdr_InfoAuto, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
terminarviaje_1(TerminarViajeArgs arg1,  CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, terminarViaje,
		(xdrproc_t) xdr_TerminarViajeArgs, (caddr_t) &arg1,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

InfoServicio *
estadoservicio_1(CLIENT *clnt)
{
	static InfoServicio clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	 if (clnt_call (clnt, estadoServicio, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_InfoServicio, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
