/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "estructura.h"

bool_t
xdr_PosicionPasajero (XDR *xdrs, PosicionPasajero *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->pos_x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos_y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_PosicionFinal (XDR *xdrs, PosicionFinal *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->pos_x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos_y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InfoAuto (XDR *xdrs, InfoAuto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->pos_x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos_y))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tarifa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->placa, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InfoServicio (XDR *xdrs, InfoServicio *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ganancias))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->viajes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vehiculos_disponibles))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TerminarViajeArgs (XDR *xdrs, TerminarViajeArgs *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_PosicionFinal (xdrs, &objp->posicion_final))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->costo_viaje))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->placa, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
