/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ESTRUCTURA_H_RPCGEN
#define _ESTRUCTURA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct PosicionPasajero {
	int pos_x;
	int pos_y;
};
typedef struct PosicionPasajero PosicionPasajero;

struct PosicionFinal {
	int pos_x;
	int pos_y;
};
typedef struct PosicionFinal PosicionFinal;

struct InfoAuto {
	int pos_x;
	int pos_y;
	char tipo[15];
	int tarifa;
	char placa[15];
};
typedef struct InfoAuto InfoAuto;

struct InfoServicio {
	int ganancias;
	int viajes;
	int vehiculos_disponibles;
};
typedef struct InfoServicio InfoServicio;

struct TerminarViajeArgs {
	PosicionFinal posicion_final;
	int costo_viaje;
	char placa[15];
};
typedef struct TerminarViajeArgs TerminarViajeArgs;

#define CALC_PROG 0x20000199
#define CALC_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define solicitarViaje 1
extern  InfoAuto * solicitarviaje_1(PosicionPasajero , CLIENT *);
extern  InfoAuto * solicitarviaje_1_svc(PosicionPasajero , struct svc_req *);
#define terminarViaje 2
extern  void * terminarviaje_1(TerminarViajeArgs , CLIENT *);
extern  void * terminarviaje_1_svc(TerminarViajeArgs , struct svc_req *);
#define estadoServicio 3
extern  InfoServicio * estadoservicio_1(CLIENT *);
extern  InfoServicio * estadoservicio_1_svc(struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define solicitarViaje 1
extern  InfoAuto * solicitarviaje_1();
extern  InfoAuto * solicitarviaje_1_svc();
#define terminarViaje 2
extern  void * terminarviaje_1();
extern  void * terminarviaje_1_svc();
#define estadoServicio 3
extern  InfoServicio * estadoservicio_1();
extern  InfoServicio * estadoservicio_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_PosicionPasajero (XDR *, PosicionPasajero*);
extern  bool_t xdr_PosicionFinal (XDR *, PosicionFinal*);
extern  bool_t xdr_InfoAuto (XDR *, InfoAuto*);
extern  bool_t xdr_InfoServicio (XDR *, InfoServicio*);
extern  bool_t xdr_TerminarViajeArgs (XDR *, TerminarViajeArgs*);

#else /* K&R C */
extern bool_t xdr_PosicionPasajero ();
extern bool_t xdr_PosicionFinal ();
extern bool_t xdr_InfoAuto ();
extern bool_t xdr_InfoServicio ();
extern bool_t xdr_TerminarViajeArgs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ESTRUCTURA_H_RPCGEN */
