/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>  // Para sleep()
#include "estructura.h"

void
calc_prog_1(char *host)
{
	CLIENT *clnt;
	InfoAuto  *result_1;
	PosicionPasajero solicitarviaje_1_arg1;
	void  *result_2;
	TerminarViajeArgs terminarviaje_1_arg1;
	InfoServicio  *result_3;

#ifndef	DEBUG
	clnt = clnt_create (host, CALC_PROG, CALC_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = solicitarviaje_1(solicitarviaje_1_arg1, clnt);
	if (result_1 == (InfoAuto *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = terminarviaje_1(terminarviaje_1_arg1, clnt);
	if (result_2 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = estadoservicio_1(clnt);
	if (result_3 == (InfoServicio *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	const char *host;
    
    if (argc < 3) {
        printf("usage: %s IP_ADDRESS_PORT pasajero/administrador\n", argv[0]);
        exit(1);
    }
    host = argv[1];

    if (strcmp(argv[2], "pasajero") == 0) {
        printf("Soy un pasajero\n");

        // Declarar variables
        InfoAuto *result_1;
        PosicionPasajero solicitarviaje_1_arg;
        solicitarviaje_1_arg.pos_x = rand() % 100;
        solicitarviaje_1_arg.pos_y = rand() % 100;

        printf("Posición del pasajero: (%d, %d)\n", solicitarviaje_1_arg.pos_x, solicitarviaje_1_arg.pos_y);

        // Crear cliente RPC
        CLIENT *clnt;
        clnt = clnt_create(host, CALC_PROG, CALC_VER, "tcp");
        if (clnt == NULL) {
            clnt_pcreateerror(host);
            exit(1);
        }
        printf("Cliente creado\n");

        // Llamar a la función RPC para solicitar un viaje
        result_1 = solicitarviaje_1(solicitarviaje_1_arg, clnt);
        if (result_1 == NULL) {
            clnt_perror(clnt, "call failed o ya no hay ubers disponibles");
        }

        sleep(5);  // Dormir por 5 segundos (simulación de viaje)

        //? Hasta aquí, el pasajero ya tiene un vehículo asignado

        printf("Vehículo asignado: %s\n", result_1->placa);

        // Terminar el viaje
        TerminarViajeArgs terminarviaje_1_arg;
        // Asignar memoria para la placa
        
        strcpy(terminarviaje_1_arg.placa, result_1->placa);

        terminarviaje_1_arg.posicion_final.pos_x = rand() % 100;
        terminarviaje_1_arg.posicion_final.pos_y = rand() % 100;

        // Calcular costo del viaje (suponiendo que se mide la distancia)
        terminarviaje_1_arg.costo_viaje = result_1->tarifa;

        printf("Costo del viaje: %d\n", terminarviaje_1_arg.costo_viaje);
        printf("Posición final: (%d, %d)\n", terminarviaje_1_arg.posicion_final.pos_x, terminarviaje_1_arg.posicion_final.pos_y);
        printf("Placa: %s\n", terminarviaje_1_arg.placa);

        
        // Realizar llamada para terminar el viaje
        result_1 = terminarviaje_1(terminarviaje_1_arg, clnt);
		if (result_1 == NULL) {
			clnt_perror(clnt, "call failed");
		}

    } else if (strcmp(argv[2], "administrador") == 0) {
        printf("Soy un administrador\n");
		while (1){
			// Crear cliente RPC
			CLIENT *clnt;
			clnt = clnt_create(host, CALC_PROG, CALC_VER, "tcp");
			if (clnt == NULL) {
				clnt_pcreateerror(host);
				exit(1);
			}
			printf("Cliente creado\n");

			InfoServicio *result_1;

			// Llamar a la función RPC para solicitar un viaje
			result_1 = estadoservicio_1(clnt);
			if (result_1 == NULL) {
				clnt_perror(clnt, "call failed");
			}

			printf("Ganancias: %d\n", result_1->ganancias);
			printf("Viajes: %d\n", result_1->viajes);
			sleep(2);
		}
    } else {
        printf("Tipo de usuario no reconocido\n");
        exit(1);
    }

    return 0;
}
