 #
 # $Id: Makefile,v 1.1 1997/12/23 22:03:38 alc Exp $
 #
ARCH	= rs6k_aix4

CC	= cc
CFLAGS	= -g -O

MACHDEP_OBJS=
MACHDEP_LIBS= -lm

LL	= /usr/lpp/LoadL/nfs

all:
	@if [ -f $(TmkLIB)/libTmk_udp.a    ]; then $(MAKE) water.udp    ; fi
	@if [ -f $(TmkLIB)/libTmk_udp_ll.a ]; then $(MAKE) water.udp_ll ; fi

include ../.common
