 #
 # $Id: Makefile,v 1.1 1997/12/24 07:46:58 alc Exp $
 #
ARCH	= sparc_sunos4

CC	= cc
CFLAGS	= -O2

FC	= f77
FFLAGS  = -O3

MACHDEP_OBJS= common_symbol.o
MACHDEP_LIBS=

all: zelig.udp

include ../.common

common_symbol.o: $(TmkLIB)/support/common_symbol.s
	$(AS) -o $@ $(TmkLIB)/support/common_symbol.s
