 #
 # $Id: Makefile,v 1.1 1998/09/13 07:33:30 alc Exp $
 #
ARCH	= mips_irix6

CC	= cc
CFLAGS	= -g3 -O

FC	= f77
FFLAGS  = -g3 -O

MACHDEP_OBJS= common_symbol.o
MACHDEP_LIBS=

all: Gauss.udp

include ../.common

common_symbol.o: $(TmkLIB)/support/common_symbol.s
	$(AS) -o $@ $(TmkLIB)/support/common_symbol.s
