 #
 # $Id: Makefile,v 1.1 1997/12/21 06:04:28 alc Exp $
 #
ARCH	= i386_sunos5

CC	= cc
CFLAGS	= -g -O

FC	= f77
FFLAGS  = -g -O

MACHDEP_OBJS= common_symbol.o
MACHDEP_LIBS= -lsocket -lnsl

all:

include ../.common

common_symbol.o: $(TmkLIB)/support/common_symbol.S
	$(AS) -P -DNPAGES=8192 -o $@ $(TmkLIB)/support/common_symbol.S
