/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "uber.h"

bool_t
xdr_Posicion (XDR *xdrs, Posicion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InfoAuto (XDR *xdrs, InfoAuto *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->disponible))
		 return FALSE;
	 if (!xdr_Posicion (xdrs, &objp->posicion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tipoUber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tarifa))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->placa, 7))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InfoServicio (XDR *xdrs, InfoServicio *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numViajes))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numAutosLibres))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->gananciaTotal))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ViajeInfo (XDR *xdrs, ViajeInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_Posicion (xdrs, &objp->posicion))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->costoViaje))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->placa, 7))
		 return FALSE;
	return TRUE;
}
