/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UBER_H_RPCGEN
#define _UBER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Posicion {
	int x;
	int y;
};
typedef struct Posicion Posicion;

struct InfoAuto {
	int disponible;
	Posicion posicion;
	int tipoUber;
	int tarifa;
	char *placa; // Modifique aquí.
};
typedef struct InfoAuto InfoAuto;

struct InfoServicio {
	int numViajes;
	int numAutosLibres;
	int gananciaTotal;
};
typedef struct InfoServicio InfoServicio;

struct ViajeInfo {
	Posicion posicion;
	int costoViaje;
	char *placa;
};
typedef struct ViajeInfo ViajeInfo;

#define APP_UBER 0x20000004
#define UBER_DISPLAY 1

#if defined(__STDC__) || defined(__cplusplus)
#define SolicitarViaje 1
extern  InfoAuto * solicitarviaje_1(struct Posicion *, CLIENT *);
extern  InfoAuto * solicitarviaje_1_svc(struct Posicion *, struct svc_req *);
#define TerminarViaje 2
extern  void * terminarviaje_1(struct ViajeInfo *, CLIENT *);
extern  void * terminarviaje_1_svc(struct ViajeInfo *, struct svc_req *);
#define EstadoServicio 3
extern  InfoServicio * estadoservicio_1(void *, CLIENT *);
extern  InfoServicio * estadoservicio_1_svc(void *, struct svc_req *);
extern int app_uber_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SolicitarViaje 1
extern  InfoAuto * solicitarviaje_1();
extern  InfoAuto * solicitarviaje_1_svc();
#define TerminarViaje 2
extern  void * terminarviaje_1();
extern  void * terminarviaje_1_svc();
#define EstadoServicio 3
extern  InfoServicio * estadoservicio_1();
extern  InfoServicio * estadoservicio_1_svc();
extern int app_uber_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Posicion (XDR *, Posicion*);
extern  bool_t xdr_InfoAuto (XDR *, InfoAuto*);
extern  bool_t xdr_InfoServicio (XDR *, InfoServicio*);
extern  bool_t xdr_ViajeInfo (XDR *, ViajeInfo*);

#else /* K&R C */
extern bool_t xdr_Posicion ();
extern bool_t xdr_InfoAuto ();
extern bool_t xdr_InfoServicio ();
extern bool_t xdr_ViajeInfo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UBER_H_RPCGEN */
