 #
 # $Id: Makefile,v 1.1 1997/12/14 19:42:23 alc Exp $
 #
ARCH	= i386_freebsd2

CC	= cc
CFLAGS	= -pipe -g -O2

FC	= f77
FFLAGS  = -pipe -g -O3

MACHDEP_OBJS= common_symbol.o
MACHDEP_LIBS= -lcompat

all: zelig.udp

include ../.common

common_symbol.o: $(TmkLIB)/support/common_symbol.s
	$(AS) -o $@ $(TmkLIB)/support/common_symbol.s
