 #
 # $Id: Makefile,v 10.3 1998/09/13 07:15:57 alc Exp $
 #
ARCH	= alpha_osf4

CC	= cc
CFLAGS	= -g3 -O

FC	= f77
FFLAGS	= -g3 -O

MACHDEP_OBJS= common_symbol.o
MACHDEP_LIBS=

all: shallow.udp

include ../.common

common_symbol.o: $(TmkLIB)/support/common_symbol.s
	$(AS) -o $@ $(TmkLIB)/support/common_symbol.s
